WorldWindEarth/WorldWindJava

src/gov/nasa/worldwind/symbology/milstd2525/graphics/lines/PhaseLine.java
The MilStd2525GraphicFactory class can create graphics without positions. As a result of this there is a bug in the PhaseLine class where a NPE is thrown.
The null-pointer check is an oversight that should have been in the original class.
General stability of MilStd2525-related classes.
None
None
=> Fix issue if no positions in PhaseLine determineLabelPositions method.

src/gov/nasa/worldwind/geom/Matrix.java, test/gov/nasa/worldwind/geom/MatrixTest.java
…except me found and fixed this....
fixes this one:
https://github.com/NASAWorldWind/WorldWindJava/issues/155
=> Determinant fix

src/gov/nasa/worldwindx/examples/dataimport/InstallDTED.java
Original pull-request of @gbburkhardt (see: https://github.com/NASAWorldWind/WorldWindJava/pull/137) with a fix in the InstallDTED class to allow for DTED files with upper or lowercase file extensions to be used.
This is a simple oversight that should have been included in the original class.
Allow for DTED files with upper or lowercase file extensions to be used in the installDTED example class.
None
None
=> Correct test for DTED file extension

src/gov/nasa/worldwind/avlist/AVKey.java
Migrated original pull-request of @andrewmcloud (see: https://github.com/NASAWorldWind/WorldWindJava/pull/130) here.
Fixes spelling error that have been missed.
Code-base with less spelling errors, I guess?
None
None
=> Fixed AVKey misspelling.

.gitignore, build.xml, nbproject/ide-file-targets.xml, nbproject/ide-targets.xml, nbproject/project.properties, nbproject/project.xml
Adds support for opening, building and running WorldWindJava-CE using the [Apache NetBeans](https://netbeans.org/) IDE.
NetBeans is a popular Java IDE used by many WWJ projects.
The WWJ-CE project can be opened by NetBeans immediately after cloning.
None.
Closes #7
=> Add NetBeans IDE support

src/gov/nasa/worldwind/formats/rpf/RPFDataSeries.java
Migrated the original pull-request from @rhstone (see pull-request: https://github.com/NASAWorldWind/WorldWindJava/pull/98 and the corresponding issue: https://github.com/NASAWorldWind/WorldWindJava/issues/99). According to the original [forum-post](https://forum.worldwindcentral.com/forum/world-wind-java-forums/development-help/156945-bug-in-rpfdataseries):
> There seems to be duplicate entries in enum RPFDataSeries for DATA_SERIES_D1 and DATA_SERIES_D1. Both have "D1" as and entry for the series code. We are having a problem with world wind displaying the wrong altitude with two different DTED levels. I'm using version 1586.0.0.1. Does anyone know if this is this a known bug? If so, has this been fixed in subsequent versions?
This fixes a bug where WorldWind displays the wrong altitude …
=> Correct typographical error in DTED Level 2 RPF

.travis.yml
The `.travis.yml` build script was changed to test the build with multiple JDKs.  The minimum JDK, the latest stable JDK, and an early access JDK are used.  JDKs from both Oracle and OpenJDK are used.  These include:  
- `openjdk8`
- `openjdk11`
- `oraclejdk8`
- `oraclejdk11`
- `openjdk-ea`
Failues in the early access JDK will not fail the build.
The deployment actions to GitHub Pages and GitHub Releases are constrained to `oraclejdk8`
Core component of the continuous integration process
Early warning of problems in the build.
- Increases the time for the Travis-CI build to finish
- Consumes additional Travis resources
Closes #27
=> Added multiple JDKs to the Travis-CI build

.travis.yml
The default WorldWindJava build process uses Apache Ant. This change to the Travis configuration ensures that `ant` is used even if Gradle or Maven build configuration files are detected by Travis-CI.
This change ensures the prescribed build process is followed.
Without this change, Gradle or Maven could be used by Travis instead of `ant` .
None.
PR #30 
Issue #11
=> Updated .travis.yml to force the use of Ant over Gradle

.gitignore, build.gradle, settings.gradle
This commit contains an initial gradle configuration that allows for the worldwind.jar and worldwindx.jar files to be built. The tests are run and the javadoc can also be built.
We want to migrate to gradle as our primary way of building the project.
All of the benefits of using gradle (such as dependency management etc. etc.)
None at the moment
Issue #11
=> Initial gradle build configuration

src/gov/nasa/worldwind/render/PointPlacemark.java
**Note:** Filling out this template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the
maintainer's discretion.
Fix ability to set pitch on PointPlacemark
Setting pitch on PointPlacemark is not currently working as expected
Allows developers to properly set pitch on PointPlacemark
N/A
Submitted previously as an issue on the main WorldWind repo, but has not been implemented:  https://github.com/NASAWorldWind/WorldWindJava/issues/151
=> PointPlacemark & PointPlacemarkAttributes Pitch

src/gov/nasa/worldwind/render/SurfaceText.java, src/gov/nasa/worldwindx/examples/SurfaceTextUsage.java, testFunctional/gov/nasa/worldwind/render/SurfaceTextTest.java
Added the capability to rotate `SurfaceText` objects.
- Added the `heading` property to the `SurfaceText` class
- Added methods to compute rotated text dimensions
- Added functional test
Enhances the SDK's labeling features.
This improvement adds `SurfaceText` rotation capability.
_Note: The following truncation issue was resolved through collaboration with @wcmatthysen on this pull request._
Initially, the only issue found - big texts are truncated by tile borders. 
_Note: See the conversation on this pull requests for more information on the fix._
Closes #37
=> Added SurfaceText rotation

src/gov/nasa/worldwind/awt/WorldWindowGLCanvas.java
According to @pcmehlitz, if we update to the latest version of JOGL and we do not explicitly set the surface-scale factor to 1.0 in the different constructors of WorldWindowGLCanvas, we will end up with a
surface-scale factor of 2.0 on MacOS machines with high-DPI displays. To quote his original commit-message:
"there is one more serious issue that manifests at least on OX X machines with high DPI (e.g. Macbook Pros with retina display). If we do not explicitly request pixel scale factors of 1.0 in the worldwind.awt.WorldWindowGLCanvas, we end up with factors of 2.0 after the GLCanvas is realized, which then causes all AWTInputHandler mouse callbacks to receive MouseEvents with wrong coordinates (0.5 of what they should be), which in turn causes operations that compute world coordinates …
=> MacOS surface-scale fix

.travis.yml, build.gradle
Modified the `build.gradle` and `travis.yml` files to allow us to publish snapshots to artifactory and releases to bintray depending on whether the Travis build has been done on the `develop` branch or a release-tag. The changes are similar to the way in which artifacts are published for WorldWindAndroid with a couple of differences here and there that are specific to this project.
We want to get to a point where WorldWind can be pulled in as a dependency via Maven. At the moment other non-official jars have been published that might be outdated. By adding these changes we ensure that our latest Travis builds get published so that they can be used by other 3rd-party projects.
By allowing our `develop` branch to be built on a regular basis and published as a snapshot version would allow …
=> Publish artifacts to Maven central

src/config/worldwind.xml, src/gov/nasa/worldwind/avlist/AVKey.java, src/gov/nasa/worldwind/view/BasicViewPropertyLimits.java
Restore the possibility to tilt the view when in "Flat" 2D mode, effectively creating a 2.5D view.
WorldWind v. 2.0.0 and earlier always allowed to pitch the view in 2D mode, which is a useful "core" functionality. For unknown reason, WorldWind v. 2.1.0 removed this possibility. 
The pitch buttons as well a mouse gestures (Shift-drag) are functional in all view modes.
This alter the default behavior compared to WorldView v. 2.1.0, which removed the possibility of any tilting by hard-coding it in BasicViewPropertyLimits#limitPitch(View, Angle). However, this behavior can easily be recreated by customizing the ViewPropertyLimits with setPitchLimits(Angle.ZERO, Angle.ZERO).
Tilting Globe no longer possible #51
=> Restore possibility to tilt 2D globe

src/gov/nasa/worldwind/view/orbit/FlyToOrbitViewAnimator.java
The `Globe` that is provided to the `OnSurfacePositionAnimator's` constructor could, in some situations, be null. This is especially true during startup when the `View.goTo()` method is called and the `View.getGlobe()` method returns null. As noted in the Javadocs, `View.getGlobe()` returns null if called before the first invocation of `View.apply()`. So then, instead of getting the `Globe`, and passing it on, the `OrbitView` itself is now passed along as constructor argument where the `OnSurfacePositionAnimator` can get the `Globe`, check if it is null or not and based on this determine whether it wants to try and get the `endElevation` at that point in time. If this fix is not done, the `OnSurfacePositionAnimator` could get stuck with a null `Globe` and will cause the entire application …
=> Fixed null-Globe bug in FlyToOrbitViewAnimator.

src/config/worldwind.layers.xml, src/gov/nasa/worldwind/layers/Earth/MapboxLayer.java, src/gov/nasa/worldwind/layers/TiledImageLayer.java, src/gov/nasa/worldwind/layers/mercator/BasicMercatorTiledImageLayer.java
When loading maps from Mapbox (and potentially other Mercator layer sources) a problem existed with tiles containing little or no detail (such as over water) appearing blank or empty.  
Discovered that these tile images report various image types which which need to be handled as "BufferedImage.TYPE_INT_ARGB" for the layer to display as intended.
Modified handling of image type in BasicMercatorTiledImageLayer class as follows:
Old Code
```
int type = image.getType();
if (type == BufferedImage.TYPE_CUSTOM)
{
type = BufferedImage.TYPE_INT_RGB;
}
else if (type == BufferedImage.TYPE_BYTE_INDEXED)
{
type = BufferedImage.TYPE_INT_ARGB;
}
```
New Code
```
int type = image.getType();
if (type != BufferedImage.TYPE_INT_RGB)
{
type = BufferedImage.TYPE_INT_ARGB;
}
```
Allows users to include Mapbox …
=> Address Mapbox Tiling

src/gov/nasa/worldwind/geom/Angle.java, test/gov/nasa/worldwind/geom/AngleTest.java
Made a bugfix to the `Angle` class' normalizedDegreesLatitude() method. The the latitude normalization didn't take the equator-crosses into account when determining the resulting angle's sign. This fix was
spotted by @Sufaev and was taken from the Android version of WorldWind. A couple of unit tests were also added to the `AngleTest` class to ensure that the edge-cases are correctly accounted for.
This fixes a bug in a core class, namely `Angle` that is used throughout WorldWind. This is a bug that is already fixed in the Android version of WorldWind and we should fix it here as well.
Correct angle normalization calculations.
Client code that relied on the incorrect results from this method will probably need to be fixed now as well.
Issue #46
=> Latitude normalization fix for angles > 180-deg.

.travis.yml, build.gradle, build.xml, gdal.unix.properties
Additional changes and fixes to the `build.gradle` file. In particular we can now build the MilStd2525 symbology zip file as well as launch the layer-manager example via the `runLayerManager` task. The dependency declarations have been fixed by swapping the "compile" clauses with "implementation" and vice versa (this was incorrectly declared initially). We also now have the ability to build against the system GDAL jar if required.
The `build.gradle` file is now more complete and covers most of the functionality of the ant build script. We just lack the webstart clauses.
More complete gradle build script.
None
None
=> Gradle build-script improvements

src/gov/nasa/worldwind/layers/SurfaceImageLayer.java
Change a check if an image path already exists to check against the key instead of the value in the map.  ConcurrentHashMap.contains() calls containsValue(), which will never return true when passed a String.
It's a bug.
If an image is added twice to a SurfaceImageLayer, the first one's tiles will be removed.
None that I can think of.
None created.
=> Compare key not value in SurfaceImageLayer

src/gov/nasa/worldwind/data/BasicRasterServer.java, src/gov/nasa/worldwind/data/RasterServerConfiguration.java, src/gov/nasa/worldwind/terrain/BasicElevationModel.java, src/gov/nasa/worldwind/util/DataConfigurationUtils.java, src/gov/nasa/worldwind/util/MessageStrings.properties, src/gov/nasa/worldwind/util/WWXML.java, src/gov/nasa/worldwindx/examples/layermanager/ElevationModelManagerPanel.java, src/gov/nasa/worldwindx/examples/util/WCSCoveragePanel.java
Description of the Change
• bug fix: request to WCS is clipped to Sector size of data available on the server. Mapserver will return an error if the request is for a region outside of the extent of the layer. See forum 158241. 
• add error handling for WCS operations 
• avoid memory/resource leaks 
Why Should This Be In Core?
Avoid errors when using Mapserver WCS to serve elevation data. Provide more useful error reporting when using a WCS server. Avoid memory/resource leaks.
Benefits
Potential Drawbacks
I was a bit concerned of the effect clipping the tile size to what's in the server would have on other code in the system. As far as I could tell, the ElevationModel correctly handles missing data, and if a request is made for data outside the clipped tile, the next ElevationModel in the …
=> Wcs error handling

src/gov/nasa/worldwind/symbology/milstd2525/MilStd2525TacticalSymbol.java, src/gov/nasa/worldwind/symbology/milstd2525/MilStd2525Util.java, src/gov/nasa/worldwind/symbology/milstd2525/graphics/TacticalGraphicSymbol.java
Changes pulled in from upstream PR [#5](https://github.com/NASAWorldWind/WorldWindJava/pull/5).
MilStd 2525C states direction of movement is an arrow or staff, but having an arrow differentiates the direction of movement only from a speed leader line.
Any fixes or improvements to the way in which the MilStd graphics are drawn should be added.
More accurate drawing of MilStd graphics.
None
None
=> Add arrow head for direction of movement only

src/gov/nasa/worldwind/formats/tiff/GeotiffWriter.java
Fixed incorrect count of geo keys in GeotiffWriter. It used to not subtract numbers of headers while counting geo keys.
It makes correct Geotiff export and import
It makes correct Geotiff export and import
None
None
=> Fixed wrong count of geo keys in GeotiffWriter

src/gov/nasa/worldwind/symbology/milstd2525/MilStd2525TacticalSymbol.java
**Note:** Filling out this template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the
maintainer's discretion.
Avoid NullPointerException when SPEED_LEADER_SCALE is not set and fix to anchor point of Military Symbology when using ground heading indicator.
Avoid NullPointerException when SPEED_LEADER_SCALE is not set and to properly anchor the military symbology
Prevent crashing and proving proper anchor point for military symbology
None.
=> Avoid NullPointerException and Fix the Anchor Point of Military Symbology
